#!/usr/bin/env bash
set -e
source .venv/bin/activate
python train.py
python - <<'PY'
import json, glob, os, hashlib, time
from pathlib import Path
CKPT = Path("checkpoints/nepa_hh.pt")
META = Path("checkpoints/nepa_hh.meta.json")
if CKPT.exists():
    h = hashlib.sha256()
    with open(CKPT, "rb") as f:
        for c in iter(lambda: f.read(1<<20), b""): h.update(c)
    sha = h.hexdigest()[:16]
    n_clips = len(glob.glob("data/clips/*.npz"))
    meta = {
        "arch":"NepaHHHead-256-256",
        "trained_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "n_clips": n_clips,
        "eval_metrics": json.loads(Path("checkpoints/last_eval.json").read_text()) if Path("checkpoints/last_eval.json").exists() else {},
        "version_tag": f"nepa-hh-{time.strftime('%Y.%m.%d')}-{sha[:4]}",
        "notes": "auto-generated by train_and_swap.sh"
    }
    META.write_text(json.dumps(meta, indent# (still in services/nepa-hh — completing train_and_swap.sh)

cat > train_and_swap.sh <<'SH'
#!/usr/bin/env bash
set -e
source .venv/bin/activate
python train.py
python - <<'PY'
import json, glob, hashlib, time
from pathlib import Path
CKPT = Path("checkpoints/nepa_hh.pt")
META = Path("checkpoints/nepa_hh.meta.json")
EVAL = Path("checkpoints/last_eval.json")
if CKPT.exists():
    h = hashlib.sha256()
    with open(CKPT, "rb") as f:
        for c in iter(lambda: f.read(1<<20), b""): h.update(c)
    sha = h.hexdigest()[:16]
    n_clips = len(glob.glob("data/clips/*.npz"))
    meta = {
        "arch": "NepaHHHead-256-256",
        "trained_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "n_clips": n_clips,
        "eval_metrics": json.loads(EVAL.read_text()) if EVAL.exists() else {},
        "version_tag": f"nepa-hh-{time.strftime('%Y.%m.%d')}-{sha[:4]}",
        "notes": "auto-generated by train_and_swap.sh"
    }
    META.write_text(json.dumps(meta, indent=2))
    print(f"[meta] wrote {META}  sha={sha}")
PY
echo "[swap] restarting nepa-hh to load + register new checkpoint…"
pkill -9 -f "python server.py" 2>/dev/null || true
sleep 1
nohup ./run.sh > nepa-hh.log 2>&1 &
sleep 3 && curl -s http://localhost:8765/health | python3 -m json.tool
