# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import nepa_pb2 as nepa__pb2


class NepaRuntimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InferFrame = channel.unary_unary(
                '/nepa.v1.NepaRuntime/InferFrame',
                request_serializer=nepa__pb2.FrameRequest.SerializeToString,
                response_deserializer=nepa__pb2.InferenceResult.FromString,
                )
        self.InferVideo = channel.unary_unary(
                '/nepa.v1.NepaRuntime/InferVideo',
                request_serializer=nepa__pb2.VideoRequest.SerializeToString,
                response_deserializer=nepa__pb2.InferenceResult.FromString,
                )
        self.StreamAnomalies = channel.unary_stream(
                '/nepa.v1.NepaRuntime/StreamAnomalies',
                request_serializer=nepa__pb2.StreamRequest.SerializeToString,
                response_deserializer=nepa__pb2.Anomaly.FromString,
                )
        self.Health = channel.unary_unary(
                '/nepa.v1.NepaRuntime/Health',
                request_serializer=nepa__pb2.HealthRequest.SerializeToString,
                response_deserializer=nepa__pb2.HealthResponse.FromString,
                )


class NepaRuntimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InferFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InferVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamAnomalies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NepaRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InferFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.InferFrame,
                    request_deserializer=nepa__pb2.FrameRequest.FromString,
                    response_serializer=nepa__pb2.InferenceResult.SerializeToString,
            ),
            'InferVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.InferVideo,
                    request_deserializer=nepa__pb2.VideoRequest.FromString,
                    response_serializer=nepa__pb2.InferenceResult.SerializeToString,
            ),
            'StreamAnomalies': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamAnomalies,
                    request_deserializer=nepa__pb2.StreamRequest.FromString,
                    response_serializer=nepa__pb2.Anomaly.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=nepa__pb2.HealthRequest.FromString,
                    response_serializer=nepa__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nepa.v1.NepaRuntime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NepaRuntime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InferFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nepa.v1.NepaRuntime/InferFrame',
            nepa__pb2.FrameRequest.SerializeToString,
            nepa__pb2.InferenceResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InferVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nepa.v1.NepaRuntime/InferVideo',
            nepa__pb2.VideoRequest.SerializeToString,
            nepa__pb2.InferenceResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamAnomalies(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/nepa.v1.NepaRuntime/StreamAnomalies',
            nepa__pb2.StreamRequest.SerializeToString,
            nepa__pb2.Anomaly.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nepa.v1.NepaRuntime/Health',
            nepa__pb2.HealthRequest.SerializeToString,
            nepa__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
